### ISSUE TITLE
Cannot generate any icon

### ISSUE THREAD

**Issue by ghost** [AlexDisler/cordova-icon#132]
- ImageMagick installed
- Android Platform 
- Cordova config.xml file exist

But i generating nothing with the cordova-icon command,
Is someone get the same problem?
```
 Checking Project & Icon

  ✓  platforms found: android
  ✓  icon.png exists
  ✓  config.xml exists

 Generating Icons for android
```

**Comment by bhabalhemant** [comment]
getting same issue??
