### ISSUE TITLE
Different icons for iOS and Android

### ISSUE THREAD

**Issue by ohh2ahh** [AlexDisler/cordova-icon#19]
I use different icons for iOS and Android. Would it be possible to define two source icons? Thanks for your work!

**Comment by devgeeks** [comment]
:+1: 

Even if you could just specify the png file and platform on the command line:

`cordova-icon android my-android-icon.png`

`cordova-icon ios my-ios-icon.png`

**Comment by xypaul** [comment]
@devgeeks yeah that be a great feature

**Comment by KODerFunk** [comment]
Need this!

**Comment by BrunoCartier** [comment]
Please try the latest version, the feature has been added with PR #65 thanks to @JohnCoker :)
See README for more information.
