### ISSUE TITLE
Default App Icon doesn't change on Android?

### ISSUE THREAD

**Issue by kithokit** [AlexDisler/cordova-icon#20]
Hello, May I know why the default icon doesn't change on my Android Device after following the step you provided.

The icon are generated successfully, and rebuild and deploy. But the app icon doesn't take effect.

Should we clean some cache or sth to achieve?
Or Do we need to modify the config.xml under the root of cordova project?

Thanks a lot.

**Comment by loicknuchel** [comment]
Hi,

I've got the same problem so I uninstalled app and reinstalled it and it works :)
It seems like Android has some trouble on app icon update...

Tell me if you solve your problem.

**Comment by kithokit** [comment]
Yes I solve it doing the exact same thing with you!
 Thanks your confirmation!
