### ISSUE TITLE
Doesnt work at all

### ISSUE THREAD

**Issue by ioudas210** [AlexDisler/cordova-icon#22]
C:\Users\gregc2\Desktop\ionicsignup - Copy\cordova>cordova-icon

 Checking Project & Icon

  √  platforms found: android
  ?  icon.png does not exist in the root folder

C:\Users\gregc2\Desktop\ionicsignup - Copy\cordova>cordova-ico

 Checking Project & Icon

  √  platforms found: android
  √  icon.png exists
  √  config.xml exists

 Generating Icons for android

{ [Error: Command failed: Invalid Parameter - -set
] timedOut: false, killed: false, code: 4, signal: null }

**Comment by BrunoCartier** [comment]
Hey @ioudas210, do you have any update on this?

**Comment by ioudas210** [comment]
Nah gave up. Thanks tho.

**Comment by jimior2** [comment]
didn't work on ImageMagick-6.9.3-8-Q16-x64-dll.exe, dese this work on specific version of ImageMagick?

**Comment by lifzgreat** [comment]
When installing ImageMagick on Windows, you need to check the box that says something about "legacy". That is what includes convert.exe (of which this is reliant on). You also need to change line 255 of npm\node_modules\cordova-icon\node_modules\imagemagick\imagemagick.js to be:
//exports.convert.path = 'convert';
exports.convert.path = "C:\\Program Files\\ImageMagick-7.0.2-Q16\\convert";

Chat it to whatever your path is.

**Comment by ganeSH-Ganz** [comment]
> When installing ImageMagick on Windows, you need to check the box that says something about "legacy". That is what includes convert.exe (of which this is reliant on). You also need to change line 255 of npm\node_modules\cordova-icon\node_modules\imagemagick\imagemagick.js to be:
> //exports.convert.path = 'convert';
> exports.convert.path = "C:\Program Files\ImageMagick-7.0.2-Q16\convert";
> 
> Chat it to whatever your path is.

its not working for me

**Comment by lifzgreat** [comment]
@ganeSH-Ganz just FYI, that comment was given over 3 years ago.

**Comment by ganeSH-Ganz** [comment]
but still there no proper solution for it

**Comment by lifzgreat** [comment]
Maybe not, who knows, it's from years ago, which is ancient in terms of software. I'm sure there's plenty of other solutions for sizing icons, even if it's not this tool.
