### ISSUE TITLE
Cant install 0.30 via NPM

### ISSUE THREAD

**Issue by chrleon** [AlexDisler/cordova-icon#28]
I'm starting with a 512x512 png and on my Nexus 5, the icon looks fuzzy, like it's not a perfect downsampling but rather a scaled down icon that is then sampled up 10%. 

Not sure if I'm using the latest version though, since I'm not seeing a xxhdpi version generated.
Inside the index.js file I got I only see the xhdpi line. When I try to unzip the package from this page into node modules, I get a crash.

Installed the cordova icon with 
> sudo npm install cordova-icon -g

Version returned by 
>npm list -g 

is cordova-icon 0.2.0

**Comment by BrunoCartier** [comment]
Hi,
It's related to #23.
If you want the latest code, you have to target the last commit of this repo. See [official NPM documentation](https://docs.npmjs.com/files/package.json#github-urls) about this.

**Comment by chrleon** [comment]
Thanks. I also got an error because of I changed the name of the so and didn't rebuild beige running cordova-icon. 

It then worked to add xxhdpi straight in code. Great plugin!
