### ISSUE TITLE
Fails to detect Android platform installed

### ISSUE THREAD

**Issue by tomchiverton** [AlexDisler/cordova-icon#29]
tchiverton@ev34:~/workspace/aki-app-ionic$ cordova platforms list
Installed platforms: android 3.6.4
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, ubuntu
tchiverton@ev34:~/workspace/aki-app-ionic$ cordova-icon

 Checking Project & Icon

  ✗  No cordova platforms found. Make sure you are in the root folder of your Cordova project and add platforms with 'cordova platform add'

tchiverton@ev34:~/workspace/aki-app-ionic$

**Comment by BrunoCartier** [comment]
_(more than one year later xD)_

Hi, is the problem still here?

`cordova-icon` just checks if the folder `platforms/android` is present. Could you please give us the folder hierarchy of your project, to see if there is something wrong?

**Comment by tomchiverton** [comment]
Seems fixed now
