### ISSUE TITLE
iPhone Settings - IOS 5-8

### ISSUE THREAD

**Issue by TheGoat30mil** [AlexDisler/cordova-icon#30]
Love using this plug-in and everything works great. There is one icon size that is missing for iPhone size:29 scale:3x

**Comment by BrunoCartier** [comment]
Hey,

According to [this page](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html), the only required icon with 29 as a size is at scale 1x.

Could you please give us your source for the requirement of this?

Thanks.
