### ISSUE TITLE
cordova-icon not working, with imagemagick installed

### ISSUE THREAD

**Issue by Tiagojdferreira** [AlexDisler/cordova-icon#31]
I have been trying to run cordova-icon on a project and I get the following error during " Generating Icons for android":
Error:

     Checking Project & Icon

      ✓  platforms found: android
      ✓  icon.png exists
      ✓  config.xml exists

     Generating Icons for android

      ✓  drawable/icon.png created
    { [Error: Command failed: convert: unable to open image `platforms/android/res/drawable-ldpi/icon.png':     No such file or directory @ error/blob.c/OpenBlob/2701.
     convert: WriteBlob Failed `platforms/android/res/drawable-ldpi/icon.png' @   error/png.c/MagickPNGErrorHandler/1630.
     ] timedOut: false, killed: false, code: 1, signal: null }

I have imagemagick:
Version: ImageMagick 6.9.0-3 Q16 x86_64 2015-01-09 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
Features: DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png xml zlib

And I am using OS X Yosemite version: 10.10.2

**Comment by BrunoCartier** [comment]
Hey,

A Google Drive folder works in a particular way. It seems possible that ImageMagick and/or cordova-icon can't work with it.
Could you please try to run the command on a local, "normal" folder?

**Comment by Tiagojdferreira** [comment]
same problem on ~/Desktop/myApp

**Comment by BrunoCartier** [comment]
Too bad. A Google search (that you probably already did) on your error tells me that it could be a file permissions issue. Can't help you more. Good luck, keep us informed.

**Comment by Tiagojdferreira** [comment]
It seems the problem is not with cordova-icon, as I just managed to run it on a different project.

**Comment by ritvick** [comment]
I faced this issue, Try removing and re-adding android platform.

**Comment by sbat** [comment]
I also get this error message when i use cordova version 5.1.1.:

```
{ 
	[
		Error: Command failed: convert: unable to open image `platforms/android/res/drawable-xxhdpi/icon.png': No such file or directory @ error/blob.c/OpenBlob/2701.
convert: WriteBlob Failed `platforms/android/res/drawable-xxhdpi/icon.png' @ error/png.c/MagickPNGErrorHandler/1630.
	] 
timedOut: false, killed: false, code: 1, signal: null }
```

The Cordova 5.1.1 command ```cordova platform add android``` creates only the following res-folders:

* drawable		
* drawable-land-mdpi
* drawable-port-hdpi
* drawable-xhdpi
* drawable-hdpi	
* drawable-land-xhdpi
* drawable-port-ldpi
* values
* drawable-land-hdpi
* drawable-ldpi	
* drawable-port-mdpi
* xml
* drawable-land-ldpi	
* drawable-mdpi	
* drawable-port-xhdpi

In my case does not exist the  ```drawable-xxhdpi```-folder. To solve this problem create this folder, bevor you run ```cordova-icon```:

```mkdir ./platforms/android/res/drawable-xxhdpi```

More informations:

https://github.com/AlexDisler/cordova-icon/blob/master/index.js#L50
http://cordova.apache.org/docs/en/5.1.1/config_ref_images.md.html#Icons%20and%20Splash%20Screens

@AlexDisler maybe you can check if the folder exist, bevor you create the icon? What do you think?

**Comment by Djiit** [comment]
@sbat This worked like a charm fro me ! Thx!

**Comment by zarko-tg** [comment]
I sent this pull request about a month ago - https://github.com/AlexDisler/cordova-icon/pull/42 (Conditional include of drawable/icon.png) It seems sufficient but I haven't put it to test much yet.

**Comment by BrunoCartier** [comment]
Hey, @Tiagojdferreira, is your problem solved? If so, can you please close this issue?
