### ISSUE TITLE
Problem to generate the icons 

### ISSUE THREAD

**Issue by FraGoTe** [AlexDisler/cordova-icon#36]
Checking Project & Icon

  ✓  platforms found: android
  ✓  icon.png exists
  ✓  config.xml exists

 Generating Icons for android

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

**Comment by BrunoCartier** [comment]
Hi,

Are you **absolutely** sure ImageMagick is installed and available ? It's a requirement.
See #21 and #25 that are exactly the same issue.

**Comment by FraGoTe** [comment]
You're right I forgot that but it didn't tell me anything.
