### ISSUE TITLE
Missing recommended icon sizes 

### ISSUE THREAD

**Issue by morenoh149** [AlexDisler/cordova-icon#39]
Love the tool btw. I get the following warnings when submitting a recent app
```
 Missing recommended icon file - The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0.

Missing recommended icon file - The bundle does not contain an app icon for iPad of exactly '76x76' pixels, in .png format for iOS versions >= 7.0.

Missing recommended icon file - The bundle does not contain an app icon for iPad of exactly '152x152' pixels, in .png format for iOS versions >= 7.0. 
```

**Comment by rahult** [comment]
Same here

Missing recommended icon file - The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0.

Missing recommended icon file - The bundle does not contain an app icon for iPad of exactly '76x76' pixels, in .png format for iOS versions >= 7.0.

Missing recommended icon file - The bundle does not contain an app icon for iPad of exactly '152x152' pixels, in .png format for iOS versions >= 7.0.

**Comment by brambo48** [comment]
And here also, same as described above

**Comment by BrunoCartier** [comment]
Pull request #52 has been merged. Could you please confirm that warnings are gone?

**Comment by BrunoCartier** [comment]
Closing this, since no response, and, has seen in #59, those sizes seem to be considered as "Unassigned". Feel free to re-open if needed.
