### ISSUE TITLE
spawn convert ENOENT

### ISSUE THREAD

**Issue by azachar** [AlexDisler/cordova-icon#53]
Hi there!
I am having an issue to run your  tool. It says:
 Checking Splash & Icon

  ✓  model/icon.png exists
  ✓  model/splash.png exists

 Generating Icons for ios

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn convert ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

Do you have any idea what is wrong?

Cheers,
Andrej

**Comment by BrunoCartier** [comment]
Hi,

On which platform are you ?
Are you **absolutely** sure [ImageMagick](https://github.com/AlexDisler/cordova-icon#requirements) is installed and available ? It's a requirement.

**Comment by azachar** [comment]
Thanks for your quick response. The ImageMagick was broken, after re-installation the problem disappeared.
