### ISSUE TITLE
missing icon for ipad pro 

### ISSUE THREAD

**Issue by piermariacosina** [AlexDisler/cordova-icon#67]
ipad pro icon 83.5pt is missing in the generation

**Comment by BrunoCartier** [comment]
Are you sure? It seems there in latest version (0.6.0):
`{ name : 'icon-83.5@2x.png', size : 167 }`

**Comment by piermariacosina** [comment]
you are right looks like that xcode don't pick it up automatically don't know why.

but adding it by hand from the folder works!

**Comment by mdgcat** [comment]
i have the same issue.  the icon for the ipad pro is created but it doesn't automatically get added to the build.  have to modify the `Contents.json` file to make it work.

Using: cordova@6.0.0 & cordova-ios@4.0.1

**Comment by BrunoCartier** [comment]
Closing since talking about possibly outdated problems.
Fell free to open a new issue if needed.
