### ISSUE TITLE
Icons not created and config.xml not updates?

### ISSUE THREAD

**Issue by lddd** [AlexDisler/cordova-icon#74]
Hi there,

i followed the steps installing cordova-icon. I placed a icon.png inside the root folder and executed the cordoba-icon command.

` Checking Project & Icon

  ✓  platforms found: ios, android
  ✓  icon.png exists
  ✓  config.xml exists

 Generating Icons for ios

  ✓  icon-40.png created
  ✓  icon-40@2x.png created
  ✓  icon-50.png created
  ✓  icon-60.png created`

Now where are these? I can't find. Also the config.xml seems not getting updates, is this correct?

kind regards!

**Comment by pdebruic** [comment]
look at lines 23 & 45 in this file to see where they go

https://github.com/AlexDisler/cordova-icon/blob/master/index.js

**Comment by BrunoCartier** [comment]
@pdebruic Thanks for the response.
@lddd Documentation has been updated about the fact that `config.xml` is not updated.
