### ISSUE TITLE
Error: Command failed

### ISSUE THREAD

**Issue by Wolf-P** [AlexDisler/cordova-icon#76]
Hello,

I get an error when running cordova-icon

Checking Project & Icon

  ✓  platforms found: android
  ✓  icon.png exists
  ✓  config.xml exists

 Generating Icons for android

{ [Error: Command failed: Invalid Parameter - -set
] timedOut: false, killed: false, code: 4, signal: null }

Am i missing some config? I got problems with the splashscreen aswell (but will place that in the right git)

**Comment by haard** [comment]
I got this as well, running on windows/cygwin

**Comment by haard** [comment]
Ah, it is because of a naming conflict. Putting convert from ImageMagick before system32 (or installing the cygwin package) solves the issue.

**Comment by breezyer** [comment]
had same issue on Windows - haard got it right. Problem on my side was that imagemagick was not installed correctly. Make sure to check "Install legacy components (convert.exe etc)" and be sure that imagemagick comes before system32 in environmental variables path.

**Comment by Wolf-P** [comment]
@breezyer 

> Make sure to check "Install legacy components (convert.exe etc)" 

This made it work for me

**Comment by tberne** [comment]
@breezyer what version of ImageMagik did you installed? I have installed version `ImageMagick-7.0.2-6-Q16-HDRI-x64-static.exe` but I didn't see any option like that. Indeed, in the install directory there's no `convert.exe`.

**Comment by breezyer** [comment]
I used `ImageMagick-7.0.2-2-Q16-x64-dll.exe`

**Comment by weislanes** [comment]
Try this fork: https://github.com/eberlitz/splashicon-generator
