### ISSUE TITLE
0.8.0 uses wrong folder for IOS icons

### ISSUE THREAD

**Issue by dwmkerr** [AlexDisler/cordova-icon#80]
I've just run:

```bash
npm install cordova-icon
```

It looks like the icons for IOS are being written to the `Resources` folder, as if #55 is not included.

**Comment by jeremymlane** [comment]
Looks like this was broken in 5974610

**Comment by BrunoCartier** [comment]
It was indeed a regression. It should be solved with version 0.9.0 :)

**Comment by dwmkerr** [comment]
Thanks!!
