### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by bennerhq** [AlexDisler/cordova-icon#81]
Hello,

When running "cordova-icon" i get the following error message:

$ cordova-icon --help

 Checking Project & Icon

  ✓  platforms found: ios, android
  ✓  icon.png exists
  ✓  config.xml exists

 Generating Icons for ios

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn convert ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)

Anybody have a solution?

Thanks ;) 
BR/benner

**Comment by mishawagon** [comment]
You should brew install imagemagick

Hope that helps!

**Comment by BrunoCartier** [comment]
Is your problem solved?
