### ISSUE TITLE
config.xml is not updated

### ISSUE THREAD

**Issue by clemorphy** [AlexDisler/cordova-icon#82]
Hi

When I run cordova-icon, the image files are generated but the config.xml file is not updated.
Is is normal ?
Should we edit it manually to target the generated images ?

**Comment by BrunoCartier** [comment]
Yes, this is normal. And you don't have to add any manual target path (in fact, ensure you do not have any).

`cordova-icon` generates files with good names and locations, that are automatically used when you `cordova build`.

**Comment by clemorphy** [comment]
Ok, I just read issue #40 and I had a previous `icon` tag in my xml.
I thought cordova-icon was going to add new `icon` tags, but you say there is no need of `icon` tags at all.
So I have removed my previous tag (which I added by hand), and now it seems to build just fine.
Thanx
