### ISSUE TITLE
Different icon files for different platforms

### ISSUE THREAD

**Issue by Birowsky** [AlexDisler/cordova-icon#96]
How do i provide different source images for different platforms?

iOS requires us to specify squared - no transparency image so ios can crop it. This doesn't make sense in Android, so I wanna provide different image. What's the approach?

**Comment by Birowsky** [comment]
my bad. found it

**Comment by Birowsky** [comment]
If someone asks "What did you do today?" i'll just say "noise."

**Comment by snakeman21** [comment]
May I ask how you did this? Can't find the answer myself
